### ISSUE TITLE
Taking Snapshot of View works well when using UIViewContentModeScaleAspectFill

### ISSUE THREAD

**Issue by Knights22** [IFTTT/jot#1]
If using UIViewContentModeScaleAspectFill for the image view, the returned image is distorted if it is a smaller image, taking a snapshot of view seems to work well, code below.

``` objectivec
- (void)saveButtonAction
{
    UIImage *drawnImage = [self snapshot:self.view];

    [self.jotViewController clearAll];

    ALAssetsLibrary *library = [ALAssetsLibrary new];
    [library writeImageToSavedPhotosAlbum:[drawnImage CGImage]
                              orientation:(ALAssetOrientation)[drawnImage imageOrientation]
                          completionBlock:^(NSURL *assetURL, NSError *error){
                              if (error) {
                                  NSLog(@"Error saving photo: %@", error.localizedDescription);
                              } else {
                                  NSLog(@"Saved photo to saved photos album.");
                              }
                          }];
}

- (UIImage *)snapshot:(UIView *)view
{
    UIGraphicsBeginImageContextWithOptions(view.bounds.size, YES, 0);
    [view drawViewHierarchyInRect:view.bounds afterScreenUpdates:YES];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return image;
}
```

**Comment by lauraskelton** [comment]
Thanks for checking it out! Right now I'm using it only on images that are the same size as the view. You're totally right that it's not set up right now to handle other content modes. I'm planning to update the code to handle different layout options, but for my purposes I need the final image rendering to happen at the scale of the image rather than of the (in my case smaller) view, so I can't just snapshot it.

Look for an update soon!

**Comment by Knights22** [comment]
"I need the final image rendering to happen at the scale of the image rather than of the (in my case smaller) view"

I had time to review this again, I think you 100% right, the rendering should happen at the scale of the image rather than the view as most users will be customizing a pic after taking a photo on their device. I was getting different size images from a webservice, therefore my suggestion is not a bug.
