### ISSUE TITLE
Error compilation

### ISSUE THREAD

**Issue by remirobert** [IFTTT/jot#2]
![screen shot 2015-06-03 at 20 53 50](https://cloud.githubusercontent.com/assets/3276768/7968717/b22648d4-0a32-11e5-85a2-aca151b45366.png)
![screen shot 2015-06-03 at 20 53 59](https://cloud.githubusercontent.com/assets/3276768/7968718/b26b146e-0a32-11e5-8fbc-1eefb58c4605.png)

**Comment by lauraskelton** [comment]
Hi Remi,

Could you give some more context as to what is happening and what your setup looks like? We don't see these errors on our end. Did you install with CocoaPods?

**Comment by remirobert** [comment]
Hi, yes i install it via cocoa pods, in a fresh project. 
![screen shot 2015-06-03 at 22 11 00](https://cloud.githubusercontent.com/assets/3276768/7970316/730c9bde-0a3d-11e5-8c88-69ea462fa5a7.png)
![screen shot 2015-06-03 at 22 10 54](https://cloud.githubusercontent.com/assets/3276768/7970317/735f4280-0a3d-11e5-828a-5d8c739e48f1.png)

**Comment by lauraskelton** [comment]
Are you seeing the compiler error inside of `JotViewController.h` or in your own header file?

**Comment by remirobert** [comment]
inside the JotViewController.h.

In my own view controller i have juste the basic setup in the README.

**Comment by lauraskelton** [comment]
Could you see if adding this to the top of that file fixes the issue for you? It may have to do with the way that new projects are setup in Xcode 6.

``` objc
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
```

Also, thanks for checking out jot and letting us know about the issue!

**Comment by remirobert** [comment]
Thank you, it was the solution. Now it works fine. But just one thing, because the files in the Pod, are lock, so couldn't edit it. So i put the source code in my project.

**Comment by lauraskelton** [comment]
OK, we'll get a fix ready in the next version of the pod for this. Thanks for helping us debug the issue!

**Comment by remirobert** [comment]
Thanks for you help, and felicitation for jot, it's really awesome. I proposed a pull request, be free to decline if it's not right.

**Comment by lauraskelton** [comment]
Thanks for the pull request and helping us figure out what was going on!
