### ISSUE TITLE
drawing color does not change immediately

### ISSUE THREAD

**Issue by MattSich** [IFTTT/jot#5]
If you draw something, then change the color and draw again, the first little bit of the new drawing stroke will be the old color.

**Comment by lauraskelton** [comment]
Hi @MattSich , thanks for contributing! There was a pull request earlier that fixed the switching color issue https://github.com/IFTTT/jot/pull/4

I hadn't yet pushed the cocoa pods version of Jot that included this fix, but I just did. If you switch to version 0.1.5 it should work.
